#!/bin/sh
# SPDX-FileCopyrightText: © 2014-2021 David Parsons
# SPDX-License-Identifier: MIT

set -e
#set -x

echo "VMware ESXi Unlocker 4.0.0"
echo "=========================="
echo "© 2011-2022 David Parsons"

# Ensure we only use unmodified commands
export PATH=/bin:/sbin:/usr/bin:/usr/sbin

echo Uninstalling unlocker...
BootModuleConfig.sh --remove=macos.v00 --verbose
echo Success - please now reboot the server!
