#!/bin/sh
# SPDX-FileCopyrightText: © 2014-2021 David Parsons
# SPDX-License-Identifier: MIT

#set -e
set -x

printf "VMware ESXi Unlocker 4.0.0\n"
printf "==========================\n"
printf "© 2011-2022 David Parsons\n"

# Ensure we only use unmodified commands
export PATH=/bin:/sbin:/usr/bin:/usr/sbin

printf "\nUninstalling unlocker\n"
BootModuleConfig.sh --remove=apple.v00 --verbose

# Cleanup any previous runs
rm -rf ./tmp 2>/dev/null
rm -f -f apple.* 2>/dev/null

printf "\nSuccess - please now reboot the server!\n"
