#!/bin/sh
# SPDX-FileCopyrightText: © 2014-2021 David Parsons
# SPDX-License-Identifier: MIT

set -e

echo "VMware ESXi Unlocker 4.0.0"
echo "=========================="
echo "© 2011-2022 David Parsons"
echo Installing unlocker...

# Ensure we only use unmodified commands
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
if [ $# -ne 0 ]; then
  case "$1" in
    -v)
      echo "Verbose mode"
      set -x
      ;;
    *)
      echo "Invalid switch!"
      exit 1
      ;;
  esac
fi

# Absolute path to this script
SCRIPT=$(readlink -f "$0")
#echo "$SCRIPT"

# Absolute folder to this script
SCRIPTPATH=$(dirname "$SCRIPT")
#echo "$SCRIPTPATH"

# Change to script folder for processing
cd "$SCRIPTPATH"

echo Extracting vmx.v00 contents...
# Get the GZIP/XZ/VMTAR'd VisorFS file from main bootbank (BOOTBANK1)
cp -f $1 /bootbank/vmx.v00 vmx.gz

# Extract XZ file from GZIP file
pigz $1 -d -k vmx.gz
mv $1 -f vmx vmx.xz

# Extract VMTAR file from XZ file
xz $1 -d --single-stream < vmx.xz > vmx.vtar

# Extract TAR file from VMTAR file
vmtar -x vmx.vtar $1 -o vmx.tar

# Create a tmp folder for processing the TAR disk contents and extract files
mkdir -p ./tmp
tar x $1 -f vmx.tar -C ./tmp

# Cleanup copied/extracted files
rm $1 -f vmx*

# Do the unlocking stuff
echo Patching vmx files...
python ./patchsmc patch ./tmp/bin/vmx
python ./patchsmc patch ./tmp/bin/vmx-debug
python ./patchsmc patch ./tmp/bin/vmx-stats

# Build a signed GZ/XZ/VMTAR file
echo Rebuilding vmx.v00 VMTAR file...

#  Compress files to TAR file
cd ./tmp
tar c $1 -f ../vmx.tar *
cd ..

# Create VMTAR from TAR file
vmtar -c vmx.tar $1 -o vmx.vtar 2>/dev/null

# Compress VMTAR into XZ file and add signature
xz --compress --stdout --lzma2=dict=2048KiB --check=crc32 --threads 0 --verbose vmx.vtar > vmx.xz
cat /usr/share/weasel/s.sigblob >> vmx.xz

# Compress XZ-sig to GZIP file
pigz $1 -9 -p 60 -n -T -k -S .v00 vmx.xz
mv $1 -f vmx.xz.v00 vmx.v00

# Copy to main bootbank (BOOTBANK1)
echo Copying vmx.v00 to bootbank...
cp $1 vmx.v00 /bootbank/vmx.v00

# Remove the working files
echo Cleaning up tmp files...
rm $1 -rf ./tmp
rm $1 -f vmx.*
echo Success - please now reboot the server!
